/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AvlTreeData
 */


public class AvlTreeData {
  @SerializedName("digest")
  private String digest = null;

  @SerializedName("treeFlags")
  private Integer treeFlags = null;

  @SerializedName("keyLength")
  private Integer keyLength = null;

  @SerializedName("valueLength")
  private Integer valueLength = null;

  public AvlTreeData digest(String digest) {
    this.digest = digest;
    return this;
  }

   /**
   * Get digest
   * @return digest
  **/
  @Schema(required = true, description = "")
  public String getDigest() {
    return digest;
  }

  public void setDigest(String digest) {
    this.digest = digest;
  }

  public AvlTreeData treeFlags(Integer treeFlags) {
    this.treeFlags = treeFlags;
    return this;
  }

   /**
   * Get treeFlags
   * @return treeFlags
  **/
  @Schema(description = "")
  public Integer getTreeFlags() {
    return treeFlags;
  }

  public void setTreeFlags(Integer treeFlags) {
    this.treeFlags = treeFlags;
  }

  public AvlTreeData keyLength(Integer keyLength) {
    this.keyLength = keyLength;
    return this;
  }

   /**
   * Get keyLength
   * @return keyLength
  **/
  @Schema(description = "")
  public Integer getKeyLength() {
    return keyLength;
  }

  public void setKeyLength(Integer keyLength) {
    this.keyLength = keyLength;
  }

  public AvlTreeData valueLength(Integer valueLength) {
    this.valueLength = valueLength;
    return this;
  }

   /**
   * Get valueLength
   * @return valueLength
  **/
  @Schema(description = "")
  public Integer getValueLength() {
    return valueLength;
  }

  public void setValueLength(Integer valueLength) {
    this.valueLength = valueLength;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvlTreeData avlTreeData = (AvlTreeData) o;
    return Objects.equals(this.digest, avlTreeData.digest) &&
        Objects.equals(this.treeFlags, avlTreeData.treeFlags) &&
        Objects.equals(this.keyLength, avlTreeData.keyLength) &&
        Objects.equals(this.valueLength, avlTreeData.valueLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(digest, treeFlags, keyLength, valueLength);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvlTreeData {\n");
    
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    treeFlags: ").append(toIndentedString(treeFlags)).append("\n");
    sb.append("    keyLength: ").append(toIndentedString(keyLength)).append("\n");
    sb.append("    valueLength: ").append(toIndentedString(valueLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
