/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import com.google.gson.annotations.SerializedName;

import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Transaction augmented with some useful information
 */
@Schema(description = "Transaction augmented with some useful information")

public class BlockchainTransaction {
  @SerializedName("id")
  private String id = null;

  @SerializedName("blockId")
  private String blockId = null;

  @SerializedName("inputs")
  private java.util.List<ErgoTransactionInput> inputs = new java.util.ArrayList<ErgoTransactionInput>();

  @SerializedName("dataInputs")
  private java.util.List<ErgoTransactionDataInput> dataInputs = new java.util.ArrayList<ErgoTransactionDataInput>();

  @SerializedName("outputs")
  private java.util.List<ErgoTransactionOutput> outputs = new java.util.ArrayList<ErgoTransactionOutput>();

  @SerializedName("inclusionHeight")
  private Integer inclusionHeight = null;

  @SerializedName("numConfirmations")
  private Integer numConfirmations = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("globalIndex")
  private Long globalIndex = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBlockId() {
        return blockId;
    }

    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }

    public List<ErgoTransactionInput> getInputs() {
        return inputs;
    }

    public void setInputs(List<ErgoTransactionInput> inputs) {
        this.inputs = inputs;
    }

    public List<ErgoTransactionDataInput> getDataInputs() {
        return dataInputs;
    }

    public void setDataInputs(List<ErgoTransactionDataInput> dataInputs) {
        this.dataInputs = dataInputs;
    }

    public List<ErgoTransactionOutput> getOutputs() {
        return outputs;
    }

    public void setOutputs(List<ErgoTransactionOutput> outputs) {
        this.outputs = outputs;
    }

    public Integer getInclusionHeight() {
        return inclusionHeight;
    }

    public void setInclusionHeight(Integer inclusionHeight) {
        this.inclusionHeight = inclusionHeight;
    }

    public Integer getNumConfirmations() {
        return numConfirmations;
    }

    public void setNumConfirmations(Integer numConfirmations) {
        this.numConfirmations = numConfirmations;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getGlobalIndex() {
        return globalIndex;
    }

    public void setGlobalIndex(Long globalIndex) {
        this.globalIndex = globalIndex;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
}
