/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body2
 */


public class Body2 {
  @SerializedName("mnemonic")
  private String mnemonic = null;

  @SerializedName("mnemonicPass")
  private String mnemonicPass = null;

  public Body2 mnemonic(String mnemonic) {
    this.mnemonic = mnemonic;
    return this;
  }

   /**
   * Mnemonic seed (optional)
   * @return mnemonic
  **/
  @Schema(required = true, description = "Mnemonic seed (optional)")
  public String getMnemonic() {
    return mnemonic;
  }

  public void setMnemonic(String mnemonic) {
    this.mnemonic = mnemonic;
  }

  public Body2 mnemonicPass(String mnemonicPass) {
    this.mnemonicPass = mnemonicPass;
    return this;
  }

   /**
   * Optional pass to password-protect mnemonic seed
   * @return mnemonicPass
  **/
  @Schema(description = "Optional pass to password-protect mnemonic seed")
  public String getMnemonicPass() {
    return mnemonicPass;
  }

  public void setMnemonicPass(String mnemonicPass) {
    this.mnemonicPass = mnemonicPass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return Objects.equals(this.mnemonic, body2.mnemonic) &&
        Objects.equals(this.mnemonicPass, body2.mnemonicPass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mnemonic, mnemonicPass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("    mnemonic: ").append(toIndentedString(mnemonic)).append("\n");
    sb.append("    mnemonicPass: ").append(toIndentedString(mnemonicPass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
