/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body5
 */


public class Body5 {
  @SerializedName("derivationPath")
  private String derivationPath = null;

  public Body5 derivationPath(String derivationPath) {
    this.derivationPath = derivationPath;
    return this;
  }

   /**
   * Derivation path for a new secret to derive
   * @return derivationPath
  **/
  @Schema(example = "m/1/2", required = true, description = "Derivation path for a new secret to derive")
  public String getDerivationPath() {
    return derivationPath;
  }

  public void setDerivationPath(String derivationPath) {
    this.derivationPath = derivationPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body5 body5 = (Body5) o;
    return Objects.equals(this.derivationPath, body5.derivationPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(derivationPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body5 {\n");
    
    sb.append("    derivationPath: ").append(toIndentedString(derivationPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
