/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Holds request for wallet boxes
 */
@Schema(description = "Holds request for wallet boxes")

public class BoxesRequestHolder {
  @SerializedName("targetAssets")
  private java.util.List<java.util.List> targetAssets = new java.util.ArrayList<java.util.List>();

  @SerializedName("targetBalance")
  private Long targetBalance = null;

  public BoxesRequestHolder targetAssets(java.util.List<java.util.List> targetAssets) {
    this.targetAssets = targetAssets;
    return this;
  }

  public BoxesRequestHolder addTargetAssetsItem(java.util.List targetAssetsItem) {
    this.targetAssets.add(targetAssetsItem);
    return this;
  }

   /**
   * Target assets
   * @return targetAssets
  **/
  @Schema(required = true, description = "Target assets")
  public java.util.List<java.util.List> getTargetAssets() {
    return targetAssets;
  }

  public void setTargetAssets(java.util.List<java.util.List> targetAssets) {
    this.targetAssets = targetAssets;
  }

  public BoxesRequestHolder targetBalance(Long targetBalance) {
    this.targetBalance = targetBalance;
    return this;
  }

   /**
   * Target balance
   * @return targetBalance
  **/
  @Schema(required = true, description = "Target balance")
  public Long getTargetBalance() {
    return targetBalance;
  }

  public void setTargetBalance(Long targetBalance) {
    this.targetBalance = targetBalance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoxesRequestHolder boxesRequestHolder = (BoxesRequestHolder) o;
    return Objects.equals(this.targetAssets, boxesRequestHolder.targetAssets) &&
        Objects.equals(this.targetBalance, boxesRequestHolder.targetBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetAssets, targetBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoxesRequestHolder {\n");
    
    sb.append("    targetAssets: ").append(toIndentedString(targetAssets)).append("\n");
    sb.append("    targetBalance: ").append(toIndentedString(targetBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
