/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.ScanningPredicate;
/**
 * ContainsPredicate
 */


public class ContainsPredicate extends ScanningPredicate {
  @SerializedName("register")
  private String register = null;

  @SerializedName("bytes")
  private String bytes = null;

  public ContainsPredicate register(String register) {
    this.register = register;
    return this;
  }

   /**
   * Get register
   * @return register
  **/
  @Schema(description = "")
  public String getRegister() {
    return register;
  }

  public void setRegister(String register) {
    this.register = register;
  }

  public ContainsPredicate bytes(String bytes) {
    this.bytes = bytes;
    return this;
  }

   /**
   * Get bytes
   * @return bytes
  **/
  @Schema(required = true, description = "")
  public String getBytes() {
    return bytes;
  }

  public void setBytes(String bytes) {
    this.bytes = bytes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContainsPredicate containsPredicate = (ContainsPredicate) o;
    return Objects.equals(this.register, containsPredicate.register) &&
        Objects.equals(this.bytes, containsPredicate.bytes) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(register, bytes, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContainsPredicate {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    register: ").append(toIndentedString(register)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
