/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.SigmaBoolean;
/**
 * Result of executeWithContext request (reduceToCrypto)
 */
@Schema(description = "Result of executeWithContext request (reduceToCrypto)")

public class CryptoResult {
  @SerializedName("value")
  private SigmaBoolean value = null;

  @SerializedName("cost")
  private Long cost = null;

  public CryptoResult value(SigmaBoolean value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public SigmaBoolean getValue() {
    return value;
  }

  public void setValue(SigmaBoolean value) {
    this.value = value;
  }

  public CryptoResult cost(Long cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Estimated cost of contract execution
   * @return cost
  **/
  @Schema(required = true, description = "Estimated cost of contract execution")
  public Long getCost() {
    return cost;
  }

  public void setCost(Long cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CryptoResult cryptoResult = (CryptoResult) o;
    return Objects.equals(this.value, cryptoResult.value) &&
        Objects.equals(this.cost, cryptoResult.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CryptoResult {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
