/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Fee histogram bin
 */
@Schema(description = "Fee histogram bin")

public class FeeHistogramBin {
  @SerializedName("nTxns")
  private Integer nTxns = null;

  @SerializedName("totalFee")
  private Long totalFee = null;

  public FeeHistogramBin nTxns(Integer nTxns) {
    this.nTxns = nTxns;
    return this;
  }

   /**
   * Get nTxns
   * @return nTxns
  **/
  @Schema(description = "")
  public Integer getNTxns() {
    return nTxns;
  }

  public void setNTxns(Integer nTxns) {
    this.nTxns = nTxns;
  }

  public FeeHistogramBin totalFee(Long totalFee) {
    this.totalFee = totalFee;
    return this;
  }

   /**
   * Get totalFee
   * @return totalFee
  **/
  @Schema(description = "")
  public Long getTotalFee() {
    return totalFee;
  }

  public void setTotalFee(Long totalFee) {
    this.totalFee = totalFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeHistogramBin feeHistogramBin = (FeeHistogramBin) o;
    return Objects.equals(this.nTxns, feeHistogramBin.nTxns) &&
        Objects.equals(this.totalFee, feeHistogramBin.totalFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nTxns, totalFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeHistogramBin {\n");
    
    sb.append("    nTxns: ").append(toIndentedString(nTxns)).append("\n");
    sb.append("    totalFee: ").append(toIndentedString(totalFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
