/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.ErgoTransaction;
import org.ergoplatform.restapi.client.SigmaBoolean;
/**
 * request to extract prover hints from a transaction
 */
@Schema(description = "request to extract prover hints from a transaction")

public class HintExtractionRequest {
  @SerializedName("tx")
  private ErgoTransaction tx = null;

  @SerializedName("real")
  private java.util.List<SigmaBoolean> real = new java.util.ArrayList<SigmaBoolean>();

  @SerializedName("simulated")
  private java.util.List<SigmaBoolean> simulated = new java.util.ArrayList<SigmaBoolean>();

  @SerializedName("inputsRaw")
  private java.util.List<String> inputsRaw = null;

  @SerializedName("dataInputsRaw")
  private java.util.List<String> dataInputsRaw = null;

  public HintExtractionRequest tx(ErgoTransaction tx) {
    this.tx = tx;
    return this;
  }

   /**
   * Get tx
   * @return tx
  **/
  @Schema(required = true, description = "")
  public ErgoTransaction getTx() {
    return tx;
  }

  public void setTx(ErgoTransaction tx) {
    this.tx = tx;
  }

  public HintExtractionRequest real(java.util.List<SigmaBoolean> real) {
    this.real = real;
    return this;
  }

  public HintExtractionRequest addRealItem(SigmaBoolean realItem) {
    this.real.add(realItem);
    return this;
  }

   /**
   * Real signers of the transaction
   * @return real
  **/
  @Schema(required = true, description = "Real signers of the transaction")
  public java.util.List<SigmaBoolean> getReal() {
    return real;
  }

  public void setReal(java.util.List<SigmaBoolean> real) {
    this.real = real;
  }

  public HintExtractionRequest simulated(java.util.List<SigmaBoolean> simulated) {
    this.simulated = simulated;
    return this;
  }

  public HintExtractionRequest addSimulatedItem(SigmaBoolean simulatedItem) {
    this.simulated.add(simulatedItem);
    return this;
  }

   /**
   * Simulated signers of the transaction
   * @return simulated
  **/
  @Schema(required = true, description = "Simulated signers of the transaction")
  public java.util.List<SigmaBoolean> getSimulated() {
    return simulated;
  }

  public void setSimulated(java.util.List<SigmaBoolean> simulated) {
    this.simulated = simulated;
  }

  public HintExtractionRequest inputsRaw(java.util.List<String> inputsRaw) {
    this.inputsRaw = inputsRaw;
    return this;
  }

  public HintExtractionRequest addInputsRawItem(String inputsRawItem) {
    if (this.inputsRaw == null) {
      this.inputsRaw = new java.util.ArrayList<String>();
    }
    this.inputsRaw.add(inputsRawItem);
    return this;
  }

   /**
   * Optional list of inputs to be used in serialized form
   * @return inputsRaw
  **/
  @Schema(description = "Optional list of inputs to be used in serialized form")
  public java.util.List<String> getInputsRaw() {
    return inputsRaw;
  }

  public void setInputsRaw(java.util.List<String> inputsRaw) {
    this.inputsRaw = inputsRaw;
  }

  public HintExtractionRequest dataInputsRaw(java.util.List<String> dataInputsRaw) {
    this.dataInputsRaw = dataInputsRaw;
    return this;
  }

  public HintExtractionRequest addDataInputsRawItem(String dataInputsRawItem) {
    if (this.dataInputsRaw == null) {
      this.dataInputsRaw = new java.util.ArrayList<String>();
    }
    this.dataInputsRaw.add(dataInputsRawItem);
    return this;
  }

   /**
   * Optional list of inputs to be used in serialized form
   * @return dataInputsRaw
  **/
  @Schema(description = "Optional list of inputs to be used in serialized form")
  public java.util.List<String> getDataInputsRaw() {
    return dataInputsRaw;
  }

  public void setDataInputsRaw(java.util.List<String> dataInputsRaw) {
    this.dataInputsRaw = dataInputsRaw;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HintExtractionRequest hintExtractionRequest = (HintExtractionRequest) o;
    return Objects.equals(this.tx, hintExtractionRequest.tx) &&
        Objects.equals(this.real, hintExtractionRequest.real) &&
        Objects.equals(this.simulated, hintExtractionRequest.simulated) &&
        Objects.equals(this.inputsRaw, hintExtractionRequest.inputsRaw) &&
        Objects.equals(this.dataInputsRaw, hintExtractionRequest.dataInputsRaw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tx, real, simulated, inputsRaw, dataInputsRaw);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HintExtractionRequest {\n");
    
    sb.append("    tx: ").append(toIndentedString(tx)).append("\n");
    sb.append("    real: ").append(toIndentedString(real)).append("\n");
    sb.append("    simulated: ").append(toIndentedString(simulated)).append("\n");
    sb.append("    inputsRaw: ").append(toIndentedString(inputsRaw)).append("\n");
    sb.append("    dataInputsRaw: ").append(toIndentedString(dataInputsRaw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
