/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PeersStatus
 */


public class PeersStatus {
  @SerializedName("lastIncomingMessage")
  private Long lastIncomingMessage = null;

  @SerializedName("currentNetworkTime")
  private Long currentNetworkTime = null;

  public PeersStatus lastIncomingMessage(Long lastIncomingMessage) {
    this.lastIncomingMessage = lastIncomingMessage;
    return this;
  }

   /**
   * Get lastIncomingMessage
   * @return lastIncomingMessage
  **/
  @Schema(description = "")
  public Long getLastIncomingMessage() {
    return lastIncomingMessage;
  }

  public void setLastIncomingMessage(Long lastIncomingMessage) {
    this.lastIncomingMessage = lastIncomingMessage;
  }

  public PeersStatus currentNetworkTime(Long currentNetworkTime) {
    this.currentNetworkTime = currentNetworkTime;
    return this;
  }

   /**
   * Get currentNetworkTime
   * @return currentNetworkTime
  **/
  @Schema(required = true, description = "")
  public Long getCurrentNetworkTime() {
    return currentNetworkTime;
  }

  public void setCurrentNetworkTime(Long currentNetworkTime) {
    this.currentNetworkTime = currentNetworkTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeersStatus peersStatus = (PeersStatus) o;
    return Objects.equals(this.lastIncomingMessage, peersStatus.lastIncomingMessage) &&
        Objects.equals(this.currentNetworkTime, peersStatus.currentNetworkTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastIncomingMessage, currentNetworkTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeersStatus {\n");
    
    sb.append("    lastIncomingMessage: ").append(toIndentedString(lastIncomingMessage)).append("\n");
    sb.append("    currentNetworkTime: ").append(toIndentedString(currentNetworkTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
