/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.BlockHeader;
/**
 * PopowHeader
 */


public class PopowHeader {
  @SerializedName("header")
  private BlockHeader header = null;

  @SerializedName("interlinks")
  private java.util.List<String> interlinks = new java.util.ArrayList<String>();

  public PopowHeader header(BlockHeader header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @Schema(required = true, description = "")
  public BlockHeader getHeader() {
    return header;
  }

  public void setHeader(BlockHeader header) {
    this.header = header;
  }

  public PopowHeader interlinks(java.util.List<String> interlinks) {
    this.interlinks = interlinks;
    return this;
  }

  public PopowHeader addInterlinksItem(String interlinksItem) {
    this.interlinks.add(interlinksItem);
    return this;
  }

   /**
   * Array of header interlinks
   * @return interlinks
  **/
  @Schema(required = true, description = "Array of header interlinks")
  public java.util.List<String> getInterlinks() {
    return interlinks;
  }

  public void setInterlinks(java.util.List<String> interlinks) {
    this.interlinks = interlinks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PopowHeader popowHeader = (PopowHeader) o;
    return Objects.equals(this.header, popowHeader.header) &&
        Objects.equals(this.interlinks, popowHeader.interlinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, interlinks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PopowHeader {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    interlinks: ").append(toIndentedString(interlinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
