/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PreHeader
 */


public class PreHeader {
  @SerializedName("timestamp")
  private Integer timestamp = null;

  @SerializedName("version")
  private Integer version = null;

  @SerializedName("nBits")
  private Long nBits = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("parentId")
  private String parentId = null;

  @SerializedName("votes")
  private String votes = null;

  @SerializedName("minerPk")
  private String minerPk = null;

  public PreHeader timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(required = true, description = "")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }

  public PreHeader version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(required = true, description = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public PreHeader nBits(Long nBits) {
    this.nBits = nBits;
    return this;
  }

   /**
   * Get nBits
   * minimum: 0
   * @return nBits
  **/
  @Schema(example = "19857408", required = true, description = "")
  public Long getNBits() {
    return nBits;
  }

  public void setNBits(Long nBits) {
    this.nBits = nBits;
  }

  public PreHeader height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * minimum: 0
   * @return height
  **/
  @Schema(example = "667", required = true, description = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public PreHeader parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(required = true, description = "")
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public PreHeader votes(String votes) {
    this.votes = votes;
    return this;
  }

   /**
   * Get votes
   * @return votes
  **/
  @Schema(required = true, description = "")
  public String getVotes() {
    return votes;
  }

  public void setVotes(String votes) {
    this.votes = votes;
  }

  public PreHeader minerPk(String minerPk) {
    this.minerPk = minerPk;
    return this;
  }

   /**
   * Get minerPk
   * @return minerPk
  **/
  @Schema(example = "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798", description = "")
  public String getMinerPk() {
    return minerPk;
  }

  public void setMinerPk(String minerPk) {
    this.minerPk = minerPk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreHeader preHeader = (PreHeader) o;
    return Objects.equals(this.timestamp, preHeader.timestamp) &&
        Objects.equals(this.version, preHeader.version) &&
        Objects.equals(this.nBits, preHeader.nBits) &&
        Objects.equals(this.height, preHeader.height) &&
        Objects.equals(this.parentId, preHeader.parentId) &&
        Objects.equals(this.votes, preHeader.votes) &&
        Objects.equals(this.minerPk, preHeader.minerPk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, version, nBits, height, parentId, votes, minerPk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreHeader {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    nBits: ").append(toIndentedString(nBits)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("    minerPk: ").append(toIndentedString(minerPk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
