/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.ErgoTransactionOutput;
/**
 * Ergo box with associated scans (their respective identifiers)
 */
@Schema(description = "Ergo box with associated scans (their respective identifiers)")

public class ScanIdsBox {
  @SerializedName("scanIds")
  private java.util.List<Integer> scanIds = new java.util.ArrayList<Integer>();

  @SerializedName("box")
  private ErgoTransactionOutput box = null;

  public ScanIdsBox scanIds(java.util.List<Integer> scanIds) {
    this.scanIds = scanIds;
    return this;
  }

  public ScanIdsBox addScanIdsItem(Integer scanIdsItem) {
    this.scanIds.add(scanIdsItem);
    return this;
  }

   /**
   * Get scanIds
   * @return scanIds
  **/
  @Schema(required = true, description = "")
  public java.util.List<Integer> getScanIds() {
    return scanIds;
  }

  public void setScanIds(java.util.List<Integer> scanIds) {
    this.scanIds = scanIds;
  }

  public ScanIdsBox box(ErgoTransactionOutput box) {
    this.box = box;
    return this;
  }

   /**
   * Get box
   * @return box
  **/
  @Schema(required = true, description = "")
  public ErgoTransactionOutput getBox() {
    return box;
  }

  public void setBox(ErgoTransactionOutput box) {
    this.box = box;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanIdsBox scanIdsBox = (ScanIdsBox) o;
    return Objects.equals(this.scanIds, scanIdsBox.scanIds) &&
        Objects.equals(this.box, scanIdsBox.box);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scanIds, box);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanIdsBox {\n");
    
    sb.append("    scanIds: ").append(toIndentedString(scanIds)).append("\n");
    sb.append("    box: ").append(toIndentedString(box)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
