/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.DhtSecret;
/**
 * Secrets used for signing
 */
@Schema(description = "Secrets used for signing")

public class TransactionSigningRequestSecrets {
  @SerializedName("dlog")
  private java.util.List<String> dlog = null;

  @SerializedName("dht")
  private java.util.List<DhtSecret> dht = null;

  public TransactionSigningRequestSecrets dlog(java.util.List<String> dlog) {
    this.dlog = dlog;
    return this;
  }

  public TransactionSigningRequestSecrets addDlogItem(String dlogItem) {
    if (this.dlog == null) {
      this.dlog = new java.util.ArrayList<String>();
    }
    this.dlog.add(dlogItem);
    return this;
  }

   /**
   * Sequence of secret exponents (DLOG secrets)
   * @return dlog
  **/
  @Schema(description = "Sequence of secret exponents (DLOG secrets)")
  public java.util.List<String> getDlog() {
    return dlog;
  }

  public void setDlog(java.util.List<String> dlog) {
    this.dlog = dlog;
  }

  public TransactionSigningRequestSecrets dht(java.util.List<DhtSecret> dht) {
    this.dht = dht;
    return this;
  }

  public TransactionSigningRequestSecrets addDhtItem(DhtSecret dhtItem) {
    if (this.dht == null) {
      this.dht = new java.util.ArrayList<DhtSecret>();
    }
    this.dht.add(dhtItem);
    return this;
  }

   /**
   * Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)
   * @return dht
  **/
  @Schema(description = "Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)")
  public java.util.List<DhtSecret> getDht() {
    return dht;
  }

  public void setDht(java.util.List<DhtSecret> dht) {
    this.dht = dht;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionSigningRequestSecrets transactionSigningRequestSecrets = (TransactionSigningRequestSecrets) o;
    return Objects.equals(this.dlog, transactionSigningRequestSecrets.dlog) &&
        Objects.equals(this.dht, transactionSigningRequestSecrets.dht);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dlog, dht);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionSigningRequestSecrets {\n");
    
    sb.append("    dlog: ").append(toIndentedString(dlog)).append("\n");
    sb.append("    dht: ").append(toIndentedString(dht)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
