/*
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * OpenAPI spec version: 4.0.12
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.restapi.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.restapi.client.ErgoTransactionDataInput;
import org.ergoplatform.restapi.client.ErgoTransactionOutput;
import org.ergoplatform.restapi.client.ErgoTransactionUnsignedInput;
/**
 * Unsigned Ergo transaction
 */
@Schema(description = "Unsigned Ergo transaction")

public class UnsignedErgoTransaction {
  @SerializedName("id")
  private String id = null;

  @SerializedName("inputs")
  private java.util.List<ErgoTransactionUnsignedInput> inputs = new java.util.ArrayList<ErgoTransactionUnsignedInput>();

  @SerializedName("dataInputs")
  private java.util.List<ErgoTransactionDataInput> dataInputs = new java.util.ArrayList<ErgoTransactionDataInput>();

  @SerializedName("outputs")
  private java.util.List<ErgoTransactionOutput> outputs = new java.util.ArrayList<ErgoTransactionOutput>();

  public UnsignedErgoTransaction id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UnsignedErgoTransaction inputs(java.util.List<ErgoTransactionUnsignedInput> inputs) {
    this.inputs = inputs;
    return this;
  }

  public UnsignedErgoTransaction addInputsItem(ErgoTransactionUnsignedInput inputsItem) {
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Unsigned inputs of the transaction
   * @return inputs
  **/
  @Schema(required = true, description = "Unsigned inputs of the transaction")
  public java.util.List<ErgoTransactionUnsignedInput> getInputs() {
    return inputs;
  }

  public void setInputs(java.util.List<ErgoTransactionUnsignedInput> inputs) {
    this.inputs = inputs;
  }

  public UnsignedErgoTransaction dataInputs(java.util.List<ErgoTransactionDataInput> dataInputs) {
    this.dataInputs = dataInputs;
    return this;
  }

  public UnsignedErgoTransaction addDataInputsItem(ErgoTransactionDataInput dataInputsItem) {
    this.dataInputs.add(dataInputsItem);
    return this;
  }

   /**
   * Data inputs of the transaction
   * @return dataInputs
  **/
  @Schema(required = true, description = "Data inputs of the transaction")
  public java.util.List<ErgoTransactionDataInput> getDataInputs() {
    return dataInputs;
  }

  public void setDataInputs(java.util.List<ErgoTransactionDataInput> dataInputs) {
    this.dataInputs = dataInputs;
  }

  public UnsignedErgoTransaction outputs(java.util.List<ErgoTransactionOutput> outputs) {
    this.outputs = outputs;
    return this;
  }

  public UnsignedErgoTransaction addOutputsItem(ErgoTransactionOutput outputsItem) {
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Outputs of the transaction
   * @return outputs
  **/
  @Schema(required = true, description = "Outputs of the transaction")
  public java.util.List<ErgoTransactionOutput> getOutputs() {
    return outputs;
  }

  public void setOutputs(java.util.List<ErgoTransactionOutput> outputs) {
    this.outputs = outputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnsignedErgoTransaction unsignedErgoTransaction = (UnsignedErgoTransaction) o;
    return Objects.equals(this.id, unsignedErgoTransaction.id) &&
        Objects.equals(this.inputs, unsignedErgoTransaction.inputs) &&
        Objects.equals(this.dataInputs, unsignedErgoTransaction.dataInputs) &&
        Objects.equals(this.outputs, unsignedErgoTransaction.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, inputs, dataInputs, outputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnsignedErgoTransaction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    dataInputs: ").append(toIndentedString(dataInputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
