/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.TokenAmount;
/**
 * Balance
 */


public class Balance {
  @SerializedName("nanoErgs")
  private Long nanoErgs = null;

  @SerializedName("tokens")
  private java.util.List<TokenAmount> tokens = null;

  public Balance nanoErgs(Long nanoErgs) {
    this.nanoErgs = nanoErgs;
    return this;
  }

   /**
   * Ergo balance
   * @return nanoErgs
  **/
  @Schema(required = true, description = "Ergo balance")
  public Long getNanoErgs() {
    return nanoErgs;
  }

  public void setNanoErgs(Long nanoErgs) {
    this.nanoErgs = nanoErgs;
  }

  public Balance tokens(java.util.List<TokenAmount> tokens) {
    this.tokens = tokens;
    return this;
  }

  public Balance addTokensItem(TokenAmount tokensItem) {
    if (this.tokens == null) {
      this.tokens = new java.util.ArrayList<TokenAmount>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Tokens balances
   * @return tokens
  **/
  @Schema(description = "Tokens balances")
  public java.util.List<TokenAmount> getTokens() {
    return tokens;
  }

  public void setTokens(java.util.List<TokenAmount> tokens) {
    this.tokens = tokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Balance balance = (Balance) o;
    return Objects.equals(this.nanoErgs, balance.nanoErgs) &&
        Objects.equals(this.tokens, balance.tokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nanoErgs, tokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Balance {\n");
    
    sb.append("    nanoErgs: ").append(toIndentedString(nanoErgs)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
