/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.BlockReferencesInfo;
import org.ergoplatform.explorer.client.model.FullBlockInfo;
/**
 * BlockSummary
 */


public class BlockSummary {
  @SerializedName("block")
  private FullBlockInfo block = null;

  @SerializedName("references")
  private BlockReferencesInfo references = null;

  public BlockSummary block(FullBlockInfo block) {
    this.block = block;
    return this;
  }

   /**
   * Get block
   * @return block
  **/
  @Schema(required = true, description = "")
  public FullBlockInfo getBlock() {
    return block;
  }

  public void setBlock(FullBlockInfo block) {
    this.block = block;
  }

  public BlockSummary references(BlockReferencesInfo references) {
    this.references = references;
    return this;
  }

   /**
   * Get references
   * @return references
  **/
  @Schema(required = true, description = "")
  public BlockReferencesInfo getReferences() {
    return references;
  }

  public void setReferences(BlockReferencesInfo references) {
    this.references = references;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockSummary blockSummary = (BlockSummary) o;
    return Objects.equals(this.block, blockSummary.block) &&
        Objects.equals(this.references, blockSummary.references);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block, references);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockSummary {\n");
    
    sb.append("    block: ").append(toIndentedString(block)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
