/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.Fields;
/**
 * BlockExtensionInfo
 */


public class BlockExtensionInfo {
  @SerializedName("headerId")
  private String headerId = null;

  @SerializedName("digest")
  private String digest = null;

  @SerializedName("fields")
  private Fields fields = null;

  public BlockExtensionInfo headerId(String headerId) {
    this.headerId = headerId;
    return this;
  }

   /**
   * ID of the corresponding header
   * @return headerId
  **/
  @Schema(required = true, description = "ID of the corresponding header")
  public String getHeaderId() {
    return headerId;
  }

  public void setHeaderId(String headerId) {
    this.headerId = headerId;
  }

  public BlockExtensionInfo digest(String digest) {
    this.digest = digest;
    return this;
  }

   /**
   * Hex-encoded extension digest
   * @return digest
  **/
  @Schema(required = true, description = "Hex-encoded extension digest")
  public String getDigest() {
    return digest;
  }

  public void setDigest(String digest) {
    this.digest = digest;
  }

  public BlockExtensionInfo fields(Fields fields) {
    this.fields = fields;
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @Schema(required = true, description = "")
  public Fields getFields() {
    return fields;
  }

  public void setFields(Fields fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockExtensionInfo blockExtensionInfo = (BlockExtensionInfo) o;
    return Objects.equals(this.headerId, blockExtensionInfo.headerId) &&
        Objects.equals(this.digest, blockExtensionInfo.digest) &&
        Objects.equals(this.fields, blockExtensionInfo.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headerId, digest, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockExtensionInfo {\n");
    
    sb.append("    headerId: ").append(toIndentedString(headerId)).append("\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
