/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InputInfo1
 */


public class InputInfo1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("value")
  private Long value = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("spendingProof")
  private String spendingProof = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("outputTransactionId")
  private String outputTransactionId = null;

  @SerializedName("outputIndex")
  private Integer outputIndex = null;

  @SerializedName("address")
  private String address = null;

  public InputInfo1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the corresponding box
   * @return id
  **/
  @Schema(required = true, description = "ID of the corresponding box")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InputInfo1 value(Long value) {
    this.value = value;
    return this;
  }

   /**
   * Number of nanoErgs in the corresponding box
   * @return value
  **/
  @Schema(description = "Number of nanoErgs in the corresponding box")
  public Long getValue() {
    return value;
  }

  public void setValue(Long value) {
    this.value = value;
  }

  public InputInfo1 index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the input in a transaction
   * @return index
  **/
  @Schema(required = true, description = "Index of the input in a transaction")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public InputInfo1 spendingProof(String spendingProof) {
    this.spendingProof = spendingProof;
    return this;
  }

   /**
   * Hex-encoded serialized sigma proof
   * @return spendingProof
  **/
  @Schema(description = "Hex-encoded serialized sigma proof")
  public String getSpendingProof() {
    return spendingProof;
  }

  public void setSpendingProof(String spendingProof) {
    this.spendingProof = spendingProof;
  }

  public InputInfo1 transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * ID of the transaction this input was used in
   * @return transactionId
  **/
  @Schema(required = true, description = "ID of the transaction this input was used in")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public InputInfo1 outputTransactionId(String outputTransactionId) {
    this.outputTransactionId = outputTransactionId;
    return this;
  }

   /**
   * ID of the transaction outputting corresponding box
   * @return outputTransactionId
  **/
  @Schema(description = "ID of the transaction outputting corresponding box")
  public String getOutputTransactionId() {
    return outputTransactionId;
  }

  public void setOutputTransactionId(String outputTransactionId) {
    this.outputTransactionId = outputTransactionId;
  }

  public InputInfo1 outputIndex(Integer outputIndex) {
    this.outputIndex = outputIndex;
    return this;
  }

   /**
   * Index of the output corresponding this input
   * @return outputIndex
  **/
  @Schema(description = "Index of the output corresponding this input")
  public Integer getOutputIndex() {
    return outputIndex;
  }

  public void setOutputIndex(Integer outputIndex) {
    this.outputIndex = outputIndex;
  }

  public InputInfo1 address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Decoded address of the corresponding box holder
   * @return address
  **/
  @Schema(description = "Decoded address of the corresponding box holder")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputInfo1 inputInfo1 = (InputInfo1) o;
    return Objects.equals(this.id, inputInfo1.id) &&
        Objects.equals(this.value, inputInfo1.value) &&
        Objects.equals(this.index, inputInfo1.index) &&
        Objects.equals(this.spendingProof, inputInfo1.spendingProof) &&
        Objects.equals(this.transactionId, inputInfo1.transactionId) &&
        Objects.equals(this.outputTransactionId, inputInfo1.outputTransactionId) &&
        Objects.equals(this.outputIndex, inputInfo1.outputIndex) &&
        Objects.equals(this.address, inputInfo1.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, value, index, spendingProof, transactionId, outputTransactionId, outputIndex, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputInfo1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    spendingProof: ").append(toIndentedString(spendingProof)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    outputTransactionId: ").append(toIndentedString(outputTransactionId)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
