/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.AdditionalRegisters;
import org.ergoplatform.explorer.client.model.AssetInstanceInfo;
/**
 * OutputInfo1
 */


public class OutputInfo1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("txId")
  private String txId = null;

  @SerializedName("value")
  private Long value = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("creationHeight")
  private Integer creationHeight = null;

  @SerializedName("ergoTree")
  private String ergoTree = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("assets")
  private java.util.List<AssetInstanceInfo> assets = null;

  @SerializedName("additionalRegisters")
  private AdditionalRegisters additionalRegisters = null;

  @SerializedName("spentTransactionId")
  private String spentTransactionId = null;

  @SerializedName("mainChain")
  private Boolean mainChain = null;

  public OutputInfo1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the box
   * @return id
  **/
  @Schema(required = true, description = "Id of the box")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OutputInfo1 txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * Id of the transaction that created the box
   * @return txId
  **/
  @Schema(required = true, description = "Id of the transaction that created the box")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public OutputInfo1 value(Long value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the box in nanoERG
   * @return value
  **/
  @Schema(required = true, description = "Value of the box in nanoERG")
  public Long getValue() {
    return value;
  }

  public void setValue(Long value) {
    this.value = value;
  }

  public OutputInfo1 index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the output in a transaction
   * @return index
  **/
  @Schema(required = true, description = "Index of the output in a transaction")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public OutputInfo1 creationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
    return this;
  }

   /**
   * Height at which the box was created
   * @return creationHeight
  **/
  @Schema(required = true, description = "Height at which the box was created")
  public Integer getCreationHeight() {
    return creationHeight;
  }

  public void setCreationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
  }

  public OutputInfo1 ergoTree(String ergoTree) {
    this.ergoTree = ergoTree;
    return this;
  }

   /**
   * Serialized ergo tree
   * @return ergoTree
  **/
  @Schema(required = true, description = "Serialized ergo tree")
  public String getErgoTree() {
    return ergoTree;
  }

  public void setErgoTree(String ergoTree) {
    this.ergoTree = ergoTree;
  }

  public OutputInfo1 address(String address) {
    this.address = address;
    return this;
  }

   /**
   * An address derived from ergo tree
   * @return address
  **/
  @Schema(required = true, description = "An address derived from ergo tree")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public OutputInfo1 assets(java.util.List<AssetInstanceInfo> assets) {
    this.assets = assets;
    return this;
  }

  public OutputInfo1 addAssetsItem(AssetInstanceInfo assetsItem) {
    if (this.assets == null) {
      this.assets = new java.util.ArrayList<AssetInstanceInfo>();
    }
    this.assets.add(assetsItem);
    return this;
  }

   /**
   * Get assets
   * @return assets
  **/
  @Schema(description = "")
  public java.util.List<AssetInstanceInfo> getAssets() {
    return assets;
  }

  public void setAssets(java.util.List<AssetInstanceInfo> assets) {
    this.assets = assets;
  }

  public OutputInfo1 additionalRegisters(AdditionalRegisters additionalRegisters) {
    this.additionalRegisters = additionalRegisters;
    return this;
  }

   /**
   * Get additionalRegisters
   * @return additionalRegisters
  **/
  @Schema(required = true, description = "")
  public AdditionalRegisters getAdditionalRegisters() {
    return additionalRegisters;
  }

  public void setAdditionalRegisters(AdditionalRegisters additionalRegisters) {
    this.additionalRegisters = additionalRegisters;
  }

  public OutputInfo1 spentTransactionId(String spentTransactionId) {
    this.spentTransactionId = spentTransactionId;
    return this;
  }

   /**
   * Transaction ID
   * @return spentTransactionId
  **/
  @Schema(description = "Transaction ID")
  public String getSpentTransactionId() {
    return spentTransactionId;
  }

  public void setSpentTransactionId(String spentTransactionId) {
    this.spentTransactionId = spentTransactionId;
  }

  public OutputInfo1 mainChain(Boolean mainChain) {
    this.mainChain = mainChain;
    return this;
  }

   /**
   * Get mainChain
   * @return mainChain
  **/
  @Schema(required = true, description = "")
  public Boolean isMainChain() {
    return mainChain;
  }

  public void setMainChain(Boolean mainChain) {
    this.mainChain = mainChain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputInfo1 outputInfo1 = (OutputInfo1) o;
    return Objects.equals(this.id, outputInfo1.id) &&
        Objects.equals(this.txId, outputInfo1.txId) &&
        Objects.equals(this.value, outputInfo1.value) &&
        Objects.equals(this.index, outputInfo1.index) &&
        Objects.equals(this.creationHeight, outputInfo1.creationHeight) &&
        Objects.equals(this.ergoTree, outputInfo1.ergoTree) &&
        Objects.equals(this.address, outputInfo1.address) &&
        Objects.equals(this.assets, outputInfo1.assets) &&
        Objects.equals(this.additionalRegisters, outputInfo1.additionalRegisters) &&
        Objects.equals(this.spentTransactionId, outputInfo1.spentTransactionId) &&
        Objects.equals(this.mainChain, outputInfo1.mainChain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, txId, value, index, creationHeight, ergoTree, address, assets, additionalRegisters, spentTransactionId, mainChain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputInfo1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    creationHeight: ").append(toIndentedString(creationHeight)).append("\n");
    sb.append("    ergoTree: ").append(toIndentedString(ergoTree)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("    additionalRegisters: ").append(toIndentedString(additionalRegisters)).append("\n");
    sb.append("    spentTransactionId: ").append(toIndentedString(spentTransactionId)).append("\n");
    sb.append("    mainChain: ").append(toIndentedString(mainChain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
