/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PowSolutionInfo
 */


public class PowSolutionInfo {
  @SerializedName("pk")
  private String pk = null;

  @SerializedName("w")
  private String w = null;

  @SerializedName("n")
  private String n = null;

  @SerializedName("d")
  private String d = null;

  public PowSolutionInfo pk(String pk) {
    this.pk = pk;
    return this;
  }

   /**
   * Miner public key
   * @return pk
  **/
  @Schema(required = true, description = "Miner public key")
  public String getPk() {
    return pk;
  }

  public void setPk(String pk) {
    this.pk = pk;
  }

  public PowSolutionInfo w(String w) {
    this.w = w;
    return this;
  }

   /**
   * Hex-encoded string
   * @return w
  **/
  @Schema(required = true, description = "Hex-encoded string")
  public String getW() {
    return w;
  }

  public void setW(String w) {
    this.w = w;
  }

  public PowSolutionInfo n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Hex-encoded string
   * @return n
  **/
  @Schema(required = true, description = "Hex-encoded string")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  public PowSolutionInfo d(String d) {
    this.d = d;
    return this;
  }

   /**
   * Autolykos.d
   * @return d
  **/
  @Schema(required = true, description = "Autolykos.d")
  public String getD() {
    return d;
  }

  public void setD(String d) {
    this.d = d;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowSolutionInfo powSolutionInfo = (PowSolutionInfo) o;
    return Objects.equals(this.pk, powSolutionInfo.pk) &&
        Objects.equals(this.w, powSolutionInfo.w) &&
        Objects.equals(this.n, powSolutionInfo.n) &&
        Objects.equals(this.d, powSolutionInfo.d);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pk, w, n, d);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowSolutionInfo {\n");
    
    sb.append("    pk: ").append(toIndentedString(pk)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    d: ").append(toIndentedString(d)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
