/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.ergoplatform.explorer.client.model.Balance;
/**
 * TotalBalance
 */


public class TotalBalance {
  @SerializedName("confirmed")
  private Balance confirmed = null;

  @SerializedName("unconfirmed")
  private Balance unconfirmed = null;

  public TotalBalance confirmed(Balance confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Get confirmed
   * @return confirmed
  **/
  @Schema(required = true, description = "")
  public Balance getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Balance confirmed) {
    this.confirmed = confirmed;
  }

  public TotalBalance unconfirmed(Balance unconfirmed) {
    this.unconfirmed = unconfirmed;
    return this;
  }

   /**
   * Get unconfirmed
   * @return unconfirmed
  **/
  @Schema(required = true, description = "")
  public Balance getUnconfirmed() {
    return unconfirmed;
  }

  public void setUnconfirmed(Balance unconfirmed) {
    this.unconfirmed = unconfirmed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TotalBalance totalBalance = (TotalBalance) o;
    return Objects.equals(this.confirmed, totalBalance.confirmed) &&
        Objects.equals(this.unconfirmed, totalBalance.unconfirmed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmed, unconfirmed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TotalBalance {\n");
    
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    unconfirmed: ").append(toIndentedString(unconfirmed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
