/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.ergoplatform.explorer.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block votes (3 bytes)
 */
@Schema(description = "Block votes (3 bytes)")

public class Tuple3ByteByteByte {
  @SerializedName("_1")
  private Integer _1 = null;

  @SerializedName("_2")
  private Integer _2 = null;

  @SerializedName("_3")
  private Integer _3 = null;

  public Tuple3ByteByteByte _1(Integer _1) {
    this._1 = _1;
    return this;
  }

   /**
   * Get _1
   * @return _1
  **/
  @Schema(required = true, description = "")
  public Integer get1() {
    return _1;
  }

  public void set1(Integer _1) {
    this._1 = _1;
  }

  public Tuple3ByteByteByte _2(Integer _2) {
    this._2 = _2;
    return this;
  }

   /**
   * Get _2
   * @return _2
  **/
  @Schema(required = true, description = "")
  public Integer get2() {
    return _2;
  }

  public void set2(Integer _2) {
    this._2 = _2;
  }

  public Tuple3ByteByteByte _3(Integer _3) {
    this._3 = _3;
    return this;
  }

   /**
   * Get _3
   * @return _3
  **/
  @Schema(required = true, description = "")
  public Integer get3() {
    return _3;
  }

  public void set3(Integer _3) {
    this._3 = _3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tuple3ByteByteByte tuple3ByteByteByte = (Tuple3ByteByteByte) o;
    return Objects.equals(this._1, tuple3ByteByteByte._1) &&
        Objects.equals(this._2, tuple3ByteByteByte._2) &&
        Objects.equals(this._3, tuple3ByteByteByte._3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1, _2, _3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tuple3ByteByteByte {\n");
    
    sb.append("    _1: ").append(toIndentedString(_1)).append("\n");
    sb.append("    _2: ").append(toIndentedString(_2)).append("\n");
    sb.append("    _3: ").append(toIndentedString(_3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
